#pragma once

#include "esp_err.h"
#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>

/**
 * Initialize and start the WebSocket server on MIMI_WS_PORT.
 * Allows external clients to interact with the Agent via JSON messages.
 *
 * Protocol:
 *   Inbound:  {"type":"message","content":"hello","chat_id":"ws_client1"}
 *   Outbound: {"type":"response","content":"Hi!","chat_id":"ws_client1"}
 */
esp_err_t ws_server_start(void);

/**
 * Send a text message to a specific WebSocket client by chat_id.
 * @param chat_id  Client identifier (assigned on connection)
 * @param text     Message text
 */
esp_err_t ws_server_send(const char *chat_id, const char *text);

/**
 * Stop the WebSocket server.
 */
esp_err_t ws_server_stop(void);

/**
 * Send a browser command to the registered extension client and wait for response.
 *
 * Command payload format mirrors extension protocol:
 *  - type: "get_dom_snapshot" / "execute_action"
 *  - request_id: auto-generated by server
 *  - extra_json: JSON object string merged into root payload (optional)
 *
 * @param type        Command type
 * @param extra_json  Optional JSON object string with extra fields
 * @param out_payload Response payload string (result JSON or error text)
 * @param out_size    Output buffer size
 * @param out_ok      True if command_result.ok=true
 * @param timeout_ms  Wait timeout
 */
esp_err_t ws_server_browser_rpc(const char *type, const char *extra_json,
                                char *out_payload, size_t out_size,
                                bool *out_ok, uint32_t timeout_ms);
